In [24]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
df = pd.read_csv('csv files/cleaned_pivot_table_filtered_for_13_tags.csv')
df.head()

,Unnamed: 0,fraud,adsh,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,OtherIncome,OtherLiabilities,PPE,Sales,ShareholdersEquity
0,2,0.0,0000002178-18-000009,20141231.0,179000.0,80184000.0,0.0,0.0,0.0,0.000000e+00,0.0,2464000.0,0.0,0.0,15744000.0,0.000000e+00,1.574970e+08
1,3,0.0,0000002178-18-000009,20151231.0,-70682000.0,97210000.0,23208000.0,-87570000.0,28783000.0,3.853222e+09,0.0,-14538000.0,0.0,143000.0,140612000.0,4.345984e+09,1.508970e+08
2,4,0.0,0000002178-18-000009,20160331.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,2.505310e+08,1.554000e+06
3,5,0.0,0000002178-18-000009,20160630.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,2.931630e+08,3.540000e+06
4,6,0.0,0000002178-18-000009,20160930.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,2.568770e+08,-9.830003e+05

In [25]:
# df.columns=df.iloc[0]
df = df.drop(columns = 'Unnamed: 0')
df.head()

,fraud,adsh,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,OtherIncome,OtherLiabilities,PPE,Sales,ShareholdersEquity
0,0.0,0000002178-18-000009,20141231.0,179000.0,80184000.0,0.0,0.0,0.0,0.000000e+00,0.0,2464000.0,0.0,0.0,15744000.0,0.000000e+00,1.574970e+08
1,0.0,0000002178-18-000009,20151231.0,-70682000.0,97210000.0,23208000.0,-87570000.0,28783000.0,3.853222e+09,0.0,-14538000.0,0.0,143000.0,140612000.0,4.345984e+09,1.508970e+08
2,0.0,0000002178-18-000009,20160331.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,2.505310e+08,1.554000e+06
3,0.0,0000002178-18-000009,20160630.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,2.931630e+08,3.540000e+06
4,0.0,0000002178-18-000009,20160930.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,2.568770e+08,-9.830003e+05

In [26]:
len(df)

48464

In [27]:
nofraud = df.loc[df.fraud == 0]

In [28]:
# nofraud.ddate.value_counts() #will filter for 20161231.0

In [29]:
len(nofraud)

47725

In [30]:
nofraud = nofraud.loc[nofraud.ddate == 20161231.0]

In [33]:
nofraud.head()

,fraud,adsh,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,OtherIncome,OtherLiabilities,PPE,Sales,ShareholdersEquity
5,0.0,0000002178-18-000009,20161231.0,106756000.0,7.875000e+07,6504000.0,1.114280e+08,2.210870e+08,2.163510e+09,0.0,4.751370e+08,4.700000e+06,1.910170e+08,4.783870e+08,2.807518e+09,5.608860e+08
20,0.0,0000002488-18-000042,20161231.0,126000000.0,2.010000e+09,90000000.0,3.825000e+09,9.210000e+08,6.611000e+09,948000000.0,2.048300e+10,1.559000e+09,4.727000e+09,2.604000e+09,9.898000e+09,5.840000e+09
26,0.0,0000002969-18-000014,20161231.0,-57400000.0,5.735000e+08,525400000.0,1.040000e+07,2.061000e+08,1.587700e+09,0.0,1.100000e+08,-7.588000e+08,1.440000e+07,4.364000e+08,1.882500e+09,8.111600e+09
34,0.0,0000003499-18-000006,20161231.0,182581000.0,8.456940e+08,130820000.0,1.110608e+09,1.655981e+09,3.176400e+08,0.0,1.490230e+09,0.000000e+00,1.104726e+09,2.852952e+09,4.356330e+08,2.694873e+09
41,0.0,0000003545-18-000021,20161231.0,7177000.0,-6.183000e+06,-16890000.0,-4.823000e+06,3.916000e+06,3.149000e+06,0.0,-7.200000e+04,2.194500e+07,-1.121000e+06,6.650000e+06,3.257300e+07,-2.526000e+06

In [31]:
len(nofraud)

5069

In [32]:
fraud = df.loc[df.fraud == 1]
len(fraud)

739

In [34]:
fraud.head()

,fraud,adsh,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,OtherIncome,OtherLiabilities,PPE,Sales,ShareholdersEquity
47725,1.0,0000023082-10-000036,20070331.0,0.000000e+00,1.050000e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.690000e+09
47726,1.0,0000023082-10-000036,20080331.0,-2.170000e+08,-7.570000e+08,1.332000e+09,2.000000e+07,2.485000e+09,2.904700e+10,3.370000e+08,-6.000000e+07,3.659000e+09,1.443000e+09,1.855000e+09,1.658700e+10,7.923000e+09
47727,1.0,0000023082-10-000036,20090331.0,7.796000e+09,2.860000e+09,1.985000e+09,1.560000e+09,-9.610000e+08,2.943500e+10,1.132600e+10,2.548200e+10,1.509000e+09,1.096400e+10,1.567400e+10,1.789100e+10,3.290000e+10
47728,1.0,0000023082-10-000036,20100331.0,7.768000e+09,2.602000e+09,1.634000e+09,2.043000e+09,-1.478000e+09,2.835100e+10,1.167100e+10,2.749800e+10,1.160000e+08,1.085300e+10,1.574900e+10,1.752400e+10,3.840900e+10
47729,1.0,0000023082-10-000054,20090331.0,0.000000e+00,2.297000e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.618000e+09

In [82]:
pd.set_option('display.precision',3)

In [87]:
a = fraud[fraud.columns[3:]]
a['Expenses'] = a['Expenses'].apply(lambda x: '{:.2f}'.format(x))
a.Expenses[0:10]

47725              0.00
47726    29047000000.00
47727    29435000000.00
47728    28351000000.00
47729              0.00
47730     7037000000.00
47731     1073000046.36
47732     8519000332.59
47733              0.00
47734      296000000.00
Name: Expenses, dtype: object

In [59]:
result = nofraud.append(fraud)
result.head()

,fraud,adsh,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,OtherIncome,OtherLiabilities,PPE,Sales,ShareholdersEquity
5,0.0,0000002178-18-000009,20161231.0,106756000.0,7.875000e+07,6504000.0,1.114280e+08,2.210870e+08,2.163510e+09,0.0,4.751370e+08,4.700000e+06,1.910170e+08,4.783870e+08,2.807518e+09,5.608860e+08
20,0.0,0000002488-18-000042,20161231.0,126000000.0,2.010000e+09,90000000.0,3.825000e+09,9.210000e+08,6.611000e+09,948000000.0,2.048300e+10,1.559000e+09,4.727000e+09,2.604000e+09,9.898000e+09,5.840000e+09
26,0.0,0000002969-18-000014,20161231.0,-57400000.0,5.735000e+08,525400000.0,1.040000e+07,2.061000e+08,1.587700e+09,0.0,1.100000e+08,-7.588000e+08,1.440000e+07,4.364000e+08,1.882500e+09,8.111600e+09
34,0.0,0000003499-18-000006,20161231.0,182581000.0,8.456940e+08,130820000.0,1.110608e+09,1.655981e+09,3.176400e+08,0.0,1.490230e+09,0.000000e+00,1.104726e+09,2.852952e+09,4.356330e+08,2.694873e+09
41,0.0,0000003545-18-000021,20161231.0,7177000.0,-6.183000e+06,-16890000.0,-4.823000e+06,3.916000e+06,3.149000e+06,0.0,-7.200000e+04,2.194500e+07,-1.121000e+06,6.650000e+06,3.257300e+07,-2.526000e+06

In [45]:
len(result) == (len(nofraud))+(len(fraud))

True

In [50]:
len(result)

5808

In [55]:
kl_div = pd.read_csv('old_notebooks/14.b.KLDivergence_for_DF.csv')
kl_div.columns

Index(['adsh', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       'sum_of_first_digits', 'total_deviation', 'fraud'],
      dtype='object')

In [56]:
kl_div = kl_div[['adsh','sum_of_first_digits', 'total_deviation']]
kl_div.head()

                   adsh  sum_of_first_digits  total_deviation
0  0000065984-18-000072                 8456         0.000339
1  0001628280-18-001324                 8968         0.000420
2  0001481792-18-000004                 1218         0.000485
3  0001193125-18-066922                 2366         0.000554
4  0001493152-18-003026                  720         0.000589

In [60]:
result = result.set_index(['adsh'])
kl_div = kl_div.set_index(['adsh'])

In [61]:
result2 = result.join(kl_div)
len(result2)

5808

In [62]:
result2.head()

,fraud,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,OtherIncome,OtherLiabilities,PPE,Sales,ShareholdersEquity,sum_of_first_digits,total_deviation
adsh,,,,,,,,,,,,,,,,,
0000002178-18-000009,0.0,20161231.0,106756000.0,7.875000e+07,6504000.0,1.114280e+08,2.210870e+08,2.163510e+09,0.0,4.751370e+08,4.700000e+06,1.910170e+08,4.783870e+08,2.807518e+09,5.608860e+08,944,0.002008
0000002488-18-000042,0.0,20161231.0,126000000.0,2.010000e+09,90000000.0,3.825000e+09,9.210000e+08,6.611000e+09,948000000.0,2.048300e+10,1.559000e+09,4.727000e+09,2.604000e+09,9.898000e+09,5.840000e+09,1162,0.003766
0000002969-18-000014,0.0,20161231.0,-57400000.0,5.735000e+08,525400000.0,1.040000e+07,2.061000e+08,1.587700e+09,0.0,1.100000e+08,-7.588000e+08,1.440000e+07,4.364000e+08,1.882500e+09,8.111600e+09,596,0.008125
0000003499-18-000006,0.0,20161231.0,182581000.0,8.456940e+08,130820000.0,1.110608e+09,1.655981e+09,3.176400e+08,0.0,1.490230e+09,0.000000e+00,1.104726e+09,2.852952e+09,4.356330e+08,2.694873e+09,660,0.023214
0000003545-18-000021,0.0,20161231.0,7177000.0,-6.183000e+06,-16890000.0,-4.823000e+06,3.916000e+06,3.149000e+06,0.0,-7.200000e+04,2.194500e+07,-1.121000e+06,6.650000e+06,3.257300e+07,-2.526000e+06,400,0.034988

In [63]:
adsh = result2

In [64]:
adsh.describe(include='all')

,fraud,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,OtherIncome,OtherLiabilities,PPE,Sales,ShareholdersEquity,sum_of_first_digits,total_deviation
count,5808.000000,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5.808000e+03,5808.000000,5808.000000
mean,0.127238,2.015580e+07,1.105152e+10,1.137501e+09,4.806700e+08,2.009455e+09,1.389230e+09,6.530296e+09,2.497405e+09,3.348148e+10,3.934067e+09,2.662017e+10,7.541869e+09,5.452177e+09,2.932198e+10,945.628099,0.014015
std,0.333268,1.583432e+04,2.227033e+11,2.212115e+10,2.510594e+09,1.644092e+10,8.728435e+09,4.655801e+10,1.652305e+10,4.275036e+11,5.897814e+10,3.603985e+11,6.080669e+10,2.834874e+10,6.134533e+11,616.225345,0.027693
min,0.000000,2.005123e+07,-7.968000e+09,-6.410500e+10,-1.636000e+10,-8.472000e+09,-6.821000e+09,-1.184900e+10,-1.493000e+06,-2.639389e+09,-1.346300e+10,-1.267902e+09,-4.202200e+07,-8.666840e+08,-1.074362e+10,10.000000,0.000339
25%,0.000000,2.016123e+07,0.000000e+00,-5.500725e+04,-4.031775e+04,6.297585e+05,2.274275e+05,1.622210e+07,0.000000e+00,1.678075e+07,1.329925e+04,3.276262e+06,4.870532e+06,2.358632e+05,6.529594e+06,522.000000,0.004546
50%,0.000000,2.016123e+07,2.297550e+07,8.643836e+06,6.772500e+06,2.208300e+07,1.908100e+07,2.248009e+08,9.871500e+06,6.082780e+08,2.290256e+07,1.878170e+08,9.303300e+07,1.289070e+08,6.216250e+08,867.000000,0.007786
75%,0.000000,2.016123e+07,4.003400e+08,1.431332e+08,1.517740e+08,3.000820e+08,3.292175e+08,1.564312e+09,3.338438e+08,4.882926e+09,3.235306e+08,3.315164e+09,1.517389e+09,1.852661e+09,5.442505e+09,1234.000000,0.014051
max,1.000000,2.016123e+07,1.351937e+13,1.222195e+12,6.535500e+10,7.029770e+11,3.551110e+11,1.581122e+12,4.316420e+11,1.978613e+13,2.519082e+12,1.750182e+13,3.085283e+12,7.909210e+11,4.544063e+13,9342.000000,0.747217

In [66]:
adsh.to_csv('739to4000_with_tags_and_KL_divergence.csv')

In [65]:
adsh.isnull().sum()

fraud                  0
ddate                  0
AccountsReceivable     0
Cash                   0
CashFlowfromOps        0
CurrentLiabilities     0
Depreciation           0
Expenses               0
IntangibleAssets       0
OtherCurrentAssets     0
OtherIncome            0
OtherLiabilities       0
PPE                    0
Sales                  0
ShareholdersEquity     0
sum_of_first_digits    0
total_deviation        0
dtype: int64

In [67]:
adsh['TotalCurrentAssets'] = adsh.AccountsReceivable+adsh.Cash+adsh.OtherCurrentAssets
adsh['CurrentRatio'] = adsh.TotalCurrentAssets/adsh.CurrentLiabilities
adsh['TotalLiabilities'] = adsh.CurrentLiabilities+adsh.OtherLiabilities
adsh['DebtToEquityRatio'] = adsh.TotalLiabilities/adsh.ShareholdersEquity
adsh['NetIncome'] = adsh.Sales - adsh.Expenses
adsh['ProfitMargin'] = adsh.NetIncome/adsh.Sales #similar to GMI
adsh['ReceivableTurnover'] = adsh.Sales/adsh.AccountsReceivable
adsh['CollectionRatio'] = 365/adsh.ReceivableTurnover
adsh['DSRI'] = adsh.AccountsReceivable/adsh.Sales
adsh['TotalAssets'] = adsh.TotalCurrentAssets+adsh.IntangibleAssets+adsh.PPE
adsh['AQI'] = 1-((adsh.TotalCurrentAssets+adsh.PPE)/adsh.TotalAssets)
adsh['DEPI'] = adsh.Depreciation/(adsh.Depreciation+adsh.PPE)
adsh['TATA'] = (adsh.NetIncome-adsh.CashFlowfromOps)/adsh.TotalAssets

In [68]:
adsh.isnull().sum()

fraud                    0
ddate                    0
AccountsReceivable       0
Cash                     0
CashFlowfromOps          0
CurrentLiabilities       0
Depreciation             0
Expenses                 0
IntangibleAssets         0
OtherCurrentAssets       0
OtherIncome              0
OtherLiabilities         0
PPE                      0
Sales                    0
ShareholdersEquity       0
sum_of_first_digits      0
total_deviation          0
TotalCurrentAssets       0
CurrentRatio           223
TotalLiabilities         0
DebtToEquityRatio      241
NetIncome                0
ProfitMargin           421
ReceivableTurnover     785
CollectionRatio        785
DSRI                   785
TotalAssets              0
AQI                    224
DEPI                   619
TATA                   115
dtype: int64

In [69]:
adsh= adsh.fillna(0)

In [70]:
df = adsh
df.head()

,fraud,ddate,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,OtherCurrentAssets,...,DebtToEquityRatio,NetIncome,ProfitMargin,ReceivableTurnover,CollectionRatio,DSRI,TotalAssets,AQI,DEPI,TATA
adsh,,,,,,,,,,,,,,,,,,,,,
0000002178-18-000009,0.0,20161231.0,106756000.0,7.875000e+07,6504000.0,1.114280e+08,2.210870e+08,2.163510e+09,0.0,4.751370e+08,...,0.539227,6.440080e+08,0.229387,26.298456,13.879142,0.038025,1.139030e+09,0.000000,0.316076,0.559690
0000002488-18-000042,0.0,20161231.0,126000000.0,2.010000e+09,90000000.0,3.825000e+09,9.210000e+08,6.611000e+09,948000000.0,2.048300e+10,...,1.464384,3.287000e+09,0.332087,78.555556,4.646393,0.012730,2.617100e+10,0.036223,0.261277,0.122158
0000002969-18-000014,0.0,20161231.0,-57400000.0,5.735000e+08,525400000.0,1.040000e+07,2.061000e+08,1.587700e+09,0.0,1.100000e+08,...,0.003057,2.948000e+08,0.156600,-32.796167,-11.129349,-0.030491,1.062500e+09,0.000000,0.320778,-0.217035
0000003499-18-000006,0.0,20161231.0,182581000.0,8.456940e+08,130820000.0,1.110608e+09,1.655981e+09,3.176400e+08,0.0,1.490230e+09,...,0.822055,1.179930e+08,0.270854,2.385971,152.977541,0.419117,5.371457e+09,0.000000,0.367267,-0.002388
0000003545-18-000021,0.0,20161231.0,7177000.0,-6.183000e+06,-16890000.0,-4.823000e+06,3.916000e+06,3.149000e+06,0.0,-7.200000e+04,...,2.353128,2.942400e+07,0.903325,4.538526,80.422589,0.220336,7.572000e+06,0.000000,0.370623,6.116482

In [71]:
df.columns

Index(['fraud', 'ddate', 'AccountsReceivable', 'Cash', 'CashFlowfromOps',
       'CurrentLiabilities', 'Depreciation', 'Expenses', 'IntangibleAssets',
       'OtherCurrentAssets', 'OtherIncome', 'OtherLiabilities', 'PPE', 'Sales',
       'ShareholdersEquity', 'sum_of_first_digits', 'total_deviation',
       'TotalCurrentAssets', 'CurrentRatio', 'TotalLiabilities',
       'DebtToEquityRatio', 'NetIncome', 'ProfitMargin', 'ReceivableTurnover',
       'CollectionRatio', 'DSRI', 'TotalAssets', 'AQI', 'DEPI', 'TATA'],
      dtype='object')

In [72]:
import numpy as np
df = df.replace([np.inf, -np.inf], np.nan)
df = df.fillna(0)

In [73]:
df.to_csv('739to4000_with_tags,KL_divergence,FinRatios.csv')

In [74]:
len(df)

5808