In [3]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

In [12]:
df = pd.read_csv('pivot_table_groupedby_adsh_with_finratios_added.csv')
df.head()

,Unnamed: 0,adsh,fraud,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,...,DebtToEquityRatio,NetIncome,ProfitMargin,ReceivableTurnover,CollectionRatio,DSRI,TotalAssets,AQI,DEPI,TATA
0,0,0000002178-18-000009,0.0,1.939190e+08,3.910830e+08,5.484600e+07,2.057540e+08,3.608060e+08,8.634819e+09,0.000000e+00,...,0.458104,3.487102e+09,0.287669,62.510228,5.839044,0.015997,2.438422e+09,0.000000,0.303202,1.407573
1,1,0000002488-18-000042,0.0,3.670000e+08,4.719000e+09,-6.800000e+07,7.206000e+09,2.143000e+09,2.505300e+10,1.123200e+10,...,2.080050,1.209000e+10,0.325499,101.207084,3.606467,0.009881,6.242400e+10,0.179931,0.235365,0.194765
2,2,0000002969-18-000014,0.0,2.337100e+09,1.333080e+10,1.091700e+09,4.203800e+09,2.294970e+10,4.373600e+09,5.649300e+09,...,0.323475,1.983300e+09,0.311992,2.719995,134.191430,0.367648,1.589743e+11,0.035536,0.285110,0.005608
3,3,0000003499-18-000006,0.0,1.797337e+09,2.928676e+09,3.604470e+08,2.394690e+09,8.263830e+09,8.957640e+08,0.000000e+00,...,1.036936,6.701600e+08,0.427965,0.871247,418.939875,1.147780,1.454291e+10,0.000000,0.579604,0.021296
4,4,0000003545-18-000021,0.0,3.092700e+07,4.077000e+06,-2.657900e+07,2.743400e+07,7.406000e+06,3.747720e+08,4.492000e+06,...,1.083978,-3.059790e+08,-4.447822,2.224367,164.091623,0.449566,1.878445e+09,0.002391,0.009501,-0.148740

In [13]:
df.isnull().sum()

Unnamed: 0               0
adsh                     0
fraud                    0
AccountsReceivable       0
Cash                     0
CashFlowfromOps          0
CurrentLiabilities       0
Depreciation             0
Expenses                 0
IntangibleAssets         0
OtherCurrentAssets       0
OtherIncome              0
OtherLiabilities         0
PPE                      0
Sales                    0
ShareholdersEquity       0
sum_of_first_digits      0
total_deviation          0
TotalCurrentAssets       0
CurrentRatio            25
TotalLiabilities         0
DebtToEquityRatio       24
NetIncome                0
ProfitMargin            63
ReceivableTurnover     496
CollectionRatio        496
DSRI                   496
TotalAssets              0
AQI                     34
DEPI                   211
TATA                    23
dtype: int64

In [14]:
df= df.fillna(0)
df.isnull().sum()

Unnamed: 0             0
adsh                   0
fraud                  0
AccountsReceivable     0
Cash                   0
CashFlowfromOps        0
CurrentLiabilities     0
Depreciation           0
Expenses               0
IntangibleAssets       0
OtherCurrentAssets     0
OtherIncome            0
OtherLiabilities       0
PPE                    0
Sales                  0
ShareholdersEquity     0
sum_of_first_digits    0
total_deviation        0
TotalCurrentAssets     0
CurrentRatio           0
TotalLiabilities       0
DebtToEquityRatio      0
NetIncome              0
ProfitMargin           0
ReceivableTurnover     0
CollectionRatio        0
DSRI                   0
TotalAssets            0
AQI                    0
DEPI                   0
TATA                   0
dtype: int64

In [15]:
df.to_csv('pivot_table_groupedby_adsh_with_finratios_and_no_nullvals.csv')

In [16]:
df.describe(include = 'all')

,Unnamed: 0,adsh,fraud,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,...,DebtToEquityRatio,NetIncome,ProfitMargin,ReceivableTurnover,CollectionRatio,DSRI,TotalAssets,AQI,DEPI,TATA
count,6032.000000,6032,6032.000000,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,...,6032.000000,6.032000e+03,6032.000000,6032.000000,6032.000000,6032.000000,6.032000e+03,6032.000000,6032.000000,6032.000000
unique,NaN,6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,0001437749-18-002506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,3015.500000,NaN,0.020060,2.432070e+10,5.070703e+09,1.415350e+09,4.503691e+09,3.947127e+09,1.967368e+10,6.689992e+09,...,NaN,2.732106e+07,NaN,NaN,NaN,NaN,1.299696e+11,0.089332,inf,NaN
std,1741.432743,NaN,0.140216,4.587488e+11,1.551257e+11,7.361133e+09,3.441292e+10,2.320210e+10,1.300799e+11,3.887676e+10,...,NaN,1.395846e+11,NaN,NaN,NaN,NaN,1.280068e+12,0.388295,NaN,NaN
min,0.000000,NaN,0.000000,-3.329931e+09,-1.043187e+11,-5.119800e+10,-1.210100e+10,-1.976000e+10,-3.260400e+10,-2.758800e+07,...,-inf,-3.690727e+12,-inf,-inf,-inf,-inf,-2.157924e+10,-0.320403,-11.707582,-inf
25%,1507.750000,NaN,0.000000,1.336965e+06,5.352600e+04,-5.047515e+05,7.126077e+06,1.165991e+06,4.954603e+07,0.000000e+00,...,0.153689,-2.004567e+08,-8.758271,0.099414,9.690833,0.026550,2.965063e+08,0.000000,0.034280,-0.110033
50%,3015.500000,NaN,0.000000,1.089030e+08,5.772550e+07,2.323700e+07,8.664400e+07,6.173050e+07,7.850689e+08,5.620771e+07,...,0.473596,-9.299250e+04,-0.053413,5.943147,35.091761,0.096142,4.372873e+09,0.016155,0.158391,-0.008734
75%,4523.250000,NaN,0.000000,1.376592e+09,5.613795e+08,4.456930e+08,9.366145e+08,1.010700e+09,5.112679e+09,1.325638e+09,...,0.898705,1.150520e+09,0.453298,17.409158,164.352228,0.450280,3.101298e+10,0.118113,0.271078,0.127532
max,6031.000000,NaN,1.000000,2.777212e+13,1.151094e+13,1.908320e+11,1.346824e+12,8.760263e+11,4.552907e+12,9.600848e+11,...,inf,6.665624e+12,inf,inf,inf,inf,4.602964e+13,28.442773,inf,inf

In [17]:
import numpy as np
df = df.replace([np.inf, -np.inf], np.nan)
df = df.fillna(0)

In [18]:
df.describe(include= 'all')

,Unnamed: 0,adsh,fraud,AccountsReceivable,Cash,CashFlowfromOps,CurrentLiabilities,Depreciation,Expenses,IntangibleAssets,...,DebtToEquityRatio,NetIncome,ProfitMargin,ReceivableTurnover,CollectionRatio,DSRI,TotalAssets,AQI,DEPI,TATA
count,6032.000000,6032,6032.000000,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,6.032000e+03,...,6.032000e+03,6.032000e+03,6032.000000,6032.000000,6.032000e+03,6.032000e+03,6.032000e+03,6032.000000,6032.000000,6032.000000
unique,NaN,6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,0001437749-18-002506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,3015.500000,NaN,0.020060,2.432070e+10,5.070703e+09,1.415350e+09,4.503691e+09,3.947127e+09,1.967368e+10,6.689992e+09,...,1.335812e+06,2.732106e+07,-466.148803,58.111602,4.502273e+05,1.233499e+03,1.299696e+11,0.089332,0.177072,-2.047647
std,1741.432743,NaN,0.140216,4.587488e+11,1.551257e+11,7.361133e+09,3.441292e+10,2.320210e+10,1.300799e+11,3.887676e+10,...,1.037472e+08,1.395846e+11,15352.469676,3427.723798,1.718367e+07,4.707855e+04,1.280068e+12,0.388295,0.262699,109.249942
min,0.000000,NaN,0.000000,-3.329931e+09,-1.043187e+11,-5.119800e+10,-1.210100e+10,-1.976000e+10,-3.260400e+10,-2.758800e+07,...,-1.146225e+04,-3.690727e+12,-723794.281250,-54992.400000,-4.322525e+08,-1.184254e+06,-2.157924e+10,-0.320403,-11.707582,-7322.854297
25%,1507.750000,NaN,0.000000,1.336965e+06,5.352600e+04,-5.047515e+05,7.126077e+06,1.165991e+06,4.954603e+07,0.000000e+00,...,1.491006e-01,-2.004567e+08,-0.823082,0.001434,3.914028e+00,1.072337e-02,2.965063e+08,0.000000,0.034176,-0.109466
50%,3015.500000,NaN,0.000000,1.089030e+08,5.772550e+07,2.323700e+07,8.664400e+07,6.173050e+07,7.850689e+08,5.620771e+07,...,4.702265e-01,-9.299250e+04,0.000000,4.906988,2.860446e+01,7.836838e-02,4.372873e+09,0.016155,0.158369,-0.008422
75%,4523.250000,NaN,0.000000,1.376592e+09,5.613795e+08,4.456930e+08,9.366145e+08,1.010700e+09,5.112679e+09,1.325638e+09,...,8.910162e-01,1.150520e+09,0.446897,15.105609,1.008477e+02,2.762950e-01,3.101298e+10,0.118113,0.271029,0.127399
max,6031.000000,NaN,1.000000,2.777212e+13,1.151094e+13,1.908320e+11,1.346824e+12,8.760263e+11,4.552907e+12,9.600848e+11,...,8.057623e+09,6.665624e+12,142975.750000,258465.000000,9.750081e+08,2.671255e+06,4.602964e+13,28.442773,5.331022,963.584906

In [19]:
df.to_csv('pivot_table_groupedby_adsh_with_finratios_and_no_nullvals_or_inf.csv')