### Final Project Requirements/notes: https://docs.google.com/document/d/1mwYbYJHkB7kpx4tNflKh54jN9_oOscw3p4k5fsmn3bc/edit

### Link with all Data: https://www.sec.gov/dera/data/financial-statement-and-notes-data-set.html
- using NUM file only for now (data set of all numeric XBRL facts presented on the primary financial statements)

In [1]:
import pandas as pd
q114numbers = pd.read_table('2015q1_notes/num.tsv', encoding ='latin1')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
#get details on all columns
q114numbers.describe(include='all')

,adsh,tag,version,ddate,qtrs,uom,dimh,iprx,value,footnote,footlen,dimn,coreg,durp,datp,dcml
count,7861900,7861900,7861900,7.861900e+06,7.861900e+06,7861900,7861900,7.234264e+06,7.741446e+06,30005,7.861900e+06,7.861900e+06,478036,7.234264e+06,7.234264e+06,7.234264e+06
unique,6996,330113,6797,NaN,NaN,3379,489433,NaN,NaN,26228,NaN,NaN,7294,NaN,NaN,NaN
top,0001507385-15-000030,StockholdersEquity,us-gaap/2014,NaN,NaN,USD,0x00000000,NaN,NaN,Fair value based on forward NYMEX natural gas ...,NaN,NaN,ParentCompany,NaN,NaN,NaN
freq,30871,83056,5527133,NaN,NaN,6753253,3205314,NaN,NaN,21,NaN,NaN,135947,NaN,NaN,NaN
mean,NaN,NaN,NaN,2.013472e+07,1.829791e+00,NaN,NaN,8.002196e-04,6.632962e+09,NaN,8.345829e-01,8.512652e-01,NaN,1.982165e-03,8.077286e-02,2.386459e+03
std,NaN,NaN,NaN,9.058241e+03,2.279711e+00,NaN,NaN,3.582441e-02,3.207053e+12,NaN,2.150437e+01,9.051028e-01,NaN,3.876579e-02,1.697204e+00,1.035419e+04
min,NaN,NaN,NaN,1.968123e+07,0.000000e+00,NaN,NaN,0.000000e+00,-7.663837e+12,NaN,0.000000e+00,0.000000e+00,NaN,-4.986305e-01,-1.500000e+01,-3.276800e+04
25%,NaN,NaN,NaN,2.013123e+07,0.000000e+00,NaN,NaN,0.000000e+00,3.610000e-01,NaN,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,-3.000000e+00
50%,NaN,NaN,NaN,2.014033e+07,1.000000e+00,NaN,NaN,0.000000e+00,1.200000e+06,NaN,0.000000e+00,1.000000e+00,NaN,0.000000e+00,0.000000e+00,-3.000000e+00
75%,NaN,NaN,NaN,2.014123e+07,4.000000e+00,NaN,NaN,0.000000e+00,2.754600e+07,NaN,0.000000e+00,1.000000e+00,NaN,1.095891e-02,0.000000e+00,0.000000e+00
max,NaN,NaN,NaN,2.113123e+07,1.500000e+02,NaN,NaN,9.000000e+00,8.000000e+15,NaN,1.334600e+04,8.000000e+00,NaN,4.986310e-01,1.500000e+01,3.276700e+04

### From "Financial Statement and Notes Data Sets" Readme:
These fields comprise a unique compound key:

1) **adsh - EDGAR accession number**: a unique identifier assigned automatically to an accepted submission by the EDGAR Filer System; The first set of numbers (0001193125) is the CIK of the entity submitting the filing. The next 2 numbers (18) represent the year. The last series of numbers represent a sequential count of submitted filings from that CIK. The count is usually, but not always, reset to 0 at the start of each calendar year.
- **TODO**: separate these numbers to identify a company or a financial filing, there were 6,492 individual filings

2) **tag** - tag used by the filer 
- **TODO**: may have to separate out first word from tag to identify broader groups such as revenue

3) **version** – if a standard tag, the taxonomy of origin, otherwise equal to adsh.

4) **ddate** - period end date

5) **qtrs** - duration in number of quarters

6) **uom** - unit of measure

7) **dimh** - 16-byte dimensional qualifier

8) **iprx** - a sequential integer used to distinguish otherwise identical facts

9) **coreg** - If specified, indicates a specific co-registrant, the parent company, or other entity (e.g., guarantor).  NULL indicates the consolidated entity.  Note that this value is a function of the dimension segments.

10) **durp** - The difference between the reported fact duration and the quarter duration (qtrs), expressed as a fraction of 1.  For example, a fact with duration of 120 days rounded to a 91-day quarter has a durp value of 29/91 = +0.3187.

11) **datp** - The difference between the reported fact date and the month-end rounded date (ddate), expressed as a fraction of 1.  For example, a fact reported for 29/Dec, with ddate rounded to 31/Dec, has a datp value of minus 2/31 = -0.0645.
 
12) **dcml** - The value of the fact "decimals" attribute, with INF represented by 32767.

In [3]:
q114numbers.isnull().sum()

adsh              0
tag               0
version           0
ddate             0
qtrs              0
uom               0
dimh              0
iprx         627636
value        120454
footnote    7831895
footlen           0
dimn              0
coreg       7383864
durp         627636
datp         627636
dcml         627636
dtype: int64

#### A lot of null values for footnotes and coregistrants (majority of rows); will remove these columns for now

In [4]:
q114numbers = q114numbers.drop(columns=['footnote','coreg'])

In [5]:
q114numbers.isnull().sum()

adsh            0
tag             0
version         0
ddate           0
qtrs            0
uom             0
dimh            0
iprx       627636
value      120454
footlen         0
dimn            0
durp       627636
datp       627636
dcml       627636
dtype: int64

In [6]:
q114numbers = q114numbers.drop(columns=['iprx','durp','datp','dcml'])

#### Didn't get rid of blank Value fields, so just get rid of those since there will still be enough data points to analyze

In [7]:
q114numbers = q114numbers.dropna()

In [8]:
q114numbers.describe(include='all') #still have 7million+ data points

,adsh,tag,version,ddate,qtrs,uom,dimh,value,footlen,dimn
count,7741446,7741446,7741446,7.741446e+06,7.741446e+06,7741446,7741446,7.741446e+06,7.741446e+06,7.741446e+06
unique,6996,329406,6796,NaN,NaN,3379,487154,NaN,NaN,NaN
top,0001507385-15-000030,StockholdersEquity,us-gaap/2014,NaN,NaN,USD,0x00000000,NaN,NaN,NaN
freq,30866,81680,5443445,NaN,NaN,6644106,3155339,NaN,NaN,NaN
mean,NaN,NaN,NaN,2.013473e+07,1.827412e+00,NaN,NaN,6.632962e+09,8.335549e-01,8.521903e-01
std,NaN,NaN,NaN,9.018806e+03,2.272527e+00,NaN,NaN,3.207053e+12,2.135654e+01,9.061745e-01
min,NaN,NaN,NaN,1.968123e+07,0.000000e+00,NaN,NaN,-7.663837e+12,0.000000e+00,0.000000e+00
25%,NaN,NaN,NaN,2.013123e+07,0.000000e+00,NaN,NaN,3.610000e-01,0.000000e+00,0.000000e+00
50%,NaN,NaN,NaN,2.014033e+07,1.000000e+00,NaN,NaN,1.200000e+06,0.000000e+00,1.000000e+00
75%,NaN,NaN,NaN,2.014123e+07,4.000000e+00,NaN,NaN,2.754600e+07,0.000000e+00,1.000000e+00
max,NaN,NaN,NaN,2.113123e+07,1.500000e+02,NaN,NaN,8.000000e+15,1.334600e+04,8.000000e+00

In [9]:
#break out adsh to cik and filing number
# s = q114numbers['adsh'].str.split('-', n = 1, expand = True)

In [10]:
# s.head()

In [11]:
# q114numbers['entity_CIK'] = s[0]
# q114numbers['filing_number'] = s[1]
# q114numbers.head()

# System; The first set of numbers (0001193125) is the CIK of the entity submitting the filing. 
# The next 2 numbers (18) represent the year. 
# The last series of numbers represent a sequential count of submitted filings from that CIK. 
# The count is usually, but not always, reset to 0 at the start of each calendar year.

In [12]:
# q414numbers = q414numbers.drop(columns =["adsh"], inplace = True)
# q414numbers = q414numbers.to_frame()

In [24]:
#Valeant's numbers
valeant_10k = q114numbers.loc[q114numbers['adsh'] == '0000885590-15-000015']
valeant_10k.head()

,adsh,tag,version,ddate,qtrs,uom,dimh,value,footlen,dimn
6051,0000885590-15-000015,AccruedLiabilitiesCurrent,us-gaap/2014,20131231,0,USD,0x00000000,1.800200e+09,0,0
6052,0000885590-15-000015,AccruedLiabilitiesCurrent,us-gaap/2014,20141231,0,USD,0x00000000,2.179400e+09,0,0
6053,0000885590-15-000015,CostsAndExpenses,us-gaap/2014,20121231,4,USD,0x00000000,3.400700e+09,0,0
6054,0000885590-15-000015,CostsAndExpenses,us-gaap/2014,20131231,4,USD,0x00000000,6.179100e+09,0,0
6055,0000885590-15-000015,CostsAndExpenses,us-gaap/2014,20141231,4,USD,0x00000000,6.223800e+09,0,0

In [25]:
all_valeant = q114numbers[q114numbers['adsh'].str.match('0000885590')]

# s.str.startswith('a', na=False)
# 0000885590

In [26]:
len(all_valeant)

2632

In [27]:
len(valeant_10k)

2632

In [28]:
valeant_nums = list(set(valeant_10k.value.abs()))
valeant_nums

[0.0,
 204800000.0,
 2.0,
 0.5,
 25600000.0,
 128000000.0,
 0.25,
 1.0,
 3.0,
 4.0,
 5.0,
 6.0,
 17.75,
 19.57,
 21.78,
 22.0,
 24.0,
 30.47,
 30.19,
 2900000.0,
 79700000.0,
 2306900000.0,
 31.44,
 4022100000.0,
 1410900000.0,
 130900000.0,
 39.11,
 54100000.0,
 1436500000.0,
 44.0,
 51.34,
 507957.0,
 54.6,
 61.8,
 62.15,
 5800000.0,
 364200000.0,
 31400000.0,
 108200000.0,
 57000000.0,
 74.88,
 85.0,
 8700000.0,
 9224700000.0,
 341500000.0,
 85500000.0,
 100.0,
 102.22,
 117.82,
 14398800000.0,
 37200000.0,
 11600000.0,
 139600000.0,
 114000000.0,
 136.59,
 137.71,
 158.0,
 14500000.0,
 884900000.0,
 449700000.0,
 160.44,
 1089700000.0,
 1092600000.0,
 17400000.0,
 43000000.0,
 196600000.0,
 299000000.0,
 219.79,
 327500000.0,
 8263500000.0,
 353100000.0,
 122700000.0,
 4193100000.0,
 20300000.0,
 1581900000.0,
 3885900000.0,
 381600000.0,
 23200000.0,
 125600000.0,
 253600000.0,
 3300000000.0,
 151200000.0,
 3200000000.0,
 500000.0,
 77300000.0,
 845300000.0,
 387400000.0,
 182600000.0,
 2179400000.0,
 29000000.0,
 3400000.0,
 566600000.0,
 10320200000.0,
 0.09,
 950600000.0,
 321.0,
 0.0275,
 134300000.0,
 851100000.0,
 6300000.0,
 108700000.0,
 159900000.0,
 876700000.0,
 31900000.0,
 572400000.0,
 214000000.0,
 60400000.0,
 1750000000.0,
 34800000.0,
 114500000.0,
 12100000.0,
 37700000.0,
 165700000.0,
 1368900000.0,
 0.0138,
 66200000.0,
 143000000.0,
 15000000.0,
 877000.0,
 1090000.0,
 197100000.0,
 17900000.0,
 683500000.0,
 200000000.0,
 46400000.0,
 353600000.0,
 72000000.0,
 481600000.0,
 1070400000.0,
 20800000.0,
 225600000.0,
 0.401,
 1.055,
 74900000.0,
 1943700000.0,
 714900000.0,
 945300000.0,
 1687700000.0,
 23700000.0,
 1047700000.0,
 794600000.0,
 717800000.0,
 1000000.0,
 77800000.0,
 615400000.0,
 52200000.0,
 0.0245,
 2026300000.0,
 515900000.0,
 3900000.0,
 630.0,
 6800000.0,
 8301200000.0,
 0.43,
 109200000.0,
 32400000.0,
 27058824.0,
 0.055,
 6332900000.0,
 883000000.0,
 63800000.0,
 473400000.0,
 12600000.0,
 191800000.0,
 38200000.0,
 0.023,
 169100000.0,
 41100000.0,
 2729100000.0,
 1013900000.0,
 750.0,
 0.523,
 248800000.0,
 1093600000.0,
 69600000.0,
 172000000.0,
 709600000.0,
 1196000000.0,
 1580000000.0,
 95200000.0,
 9600000000.0,
 866100000.0,
 21300000.0,
 277300000.0,
 226100000.0,
 635700000.0,
 10571400000.0,
 24200000.0,
 49800000.0,
 1585800000.0,
 280200000.0,
 103900000.0,
 5940700000.0,
 1500000.0,
 4400000.0,
 55600000.0,
 132400000.0,
 30000000.0,
 109700000.0,
 5434500000.0,
 928900000.0,
 1978500000.0,
 58500000.0,
 61400000.0,
 675800000.0,
 394200000.0,
 10200000.0,
 317400000.0,
 35800000.0,
 163800000.0,
 0.02,
 883500000.0,
 269100000.0,
 38700000.0,
 13100000.0,
 1216300000.0,
 1062700000.0,
 169600000.0,
 16000000.0,
 2.43,
 2578900000.0,
 18900000.0,
 146900000.0,
 44500000.0,
 249300000.0,
 0.0688,
 21800000.0,
 1711400000.0,
 47400000.0,
 75900000.0,
 280700000.0,
 24700000.0,
 152700000.0,
 155600000.0,
 53200000.0,
 2000000.0,
 78800000.0,
 27600000.0,
 104400000.0,
 158500000.0,
 1310500000.0,
 184100000.0,
 9275000000.0,
 59000000.0,
 5307000000.0,
 852600000.0,
 5998200000.0,
 7800000.0,
 189900000.0,
 10700000.0,
 36300000.0,
 192800000.0,
 39200000.0,
 500000000.0,
 116000000.0,
 13600000.0,
 167200000.0,
 20007200000.0,
 1962100000.0,
 3395700000.0,
 195700000.0,
 0.11,
 16500000.0,
 224200000.0,
 2323400000.0,
 19400000.0,
 45000000.0,
 201500000.0,
 815900000.0,
 303900000.0,
 73500000.0,
 358000000.0,
 281200000.0,
 204400000.0,
 50800000.0,
 1305200000.0,
 25200000.0,
 2500000.0,
 28100000.0,
 104900000.0,
 53700000.0,
 15391000000.0,
 1234200000.0,
 3717400000.0,
 5400000.0,
 133400000.0,
 1390700000.0,
 5640300000.0,
 3464300000.0,
 801900000.0,
 8300000.0,
 85100000.0,
 520300000.0,
 110700000.0,
 600000000.0,
 1.075,
 11200000.0,
 3065374.0,
 398100000.0,
 14100000.0,
 193300000.0,
 167700000.0,
 17000000.0,
 349800000.0,
 68200000.0,
 119400000.0,
 221800000.0,
 93800000.0,
 42600000.0,
 1885800000.0,
 320.0,
 0.075,
 19900000.0,
 915900000.0,
 45500000.0,
 122300000.0,
 455100000.0,
 0.0125,
 125200000.0,
 0.45,
 0.2,
 1354000000.0,
 2096400000.0,
 22800000.0,
 76900000.0,
 100000.0,
 1356900000.0,
 1280100000.0,
 51300000.0,
 204900000.0,
 0.043,
 259000000.0,
 28600000.0,
 6223800000.0,
 6326200000.0,
 3000000.0,
 28878538.0,
 569100000.0,
 5900000.0,
 57100000.0,
 313100000.0,
 236300000.0,
 210700000.0,
 31500000.0,
 572000000.0,
 700000000.0,
 8800000.0,
 1314400000.0,
 60000000.0,
 0.9924,
 2443700000.0,
 62900000.0,
 190900000.0,
 37300000.0,
 11700000.0,
 40200000.0,
 65800000.0,
 2307400000.0,
 43100000.0,
 171100000.0,
 1604700000.0,
 94300000.0,
 17500000.0,
 273500000.0,
 196700000.0,
 606300000.0,
 913500000.0,
 11255900000.0,
 327600000.0,
 46000000.0,
 20400000.0,
 5550000000.0,
 228100000.0,
 23300000.0,
 125700000.0,
 381700000.0,
 666200000.0,
 9575000000.0,
 51800000.0,
 600000.0,
 563800000.0,
 29100000.0,
 80300000.0,
 3500000.0,
 131500000.0,
 0.008,
 6400000.0,
 160000000.0,
 2.7,
 1.0675,
 32000000.0,
 83200000.0,
 214100000.0,
 1135700000.0,
 86100000.0,
 9300000.0,
 0.0385,
 345000000.0,
 114600000.0,
 37800000.0,
 12200000.0,
 626600000.0,
 1625000000.0,
 4264700000.0,
 783100000.0,
 15100000.0,
 40700000.0,
 66300000.0,
 1042000000.0,
 18000000.0,
 43600000.0,
 555600000.0,
 4293200000.0,
 0.444,
 72100000.0,
 148900000.0,
 430500000.0,
 0.037,
 971000000.0,
 305400000.0,
 23800000.0,
 75000000.0,
 7115000000.0,
 3226700000.0,
 9268300000.0,
 1100000.0,
 717900000.0,
 103500000.0,
 0.005,
 0.38,
 4000000.0,
 55200000.0,
 157600000.0,
 900000000.0,
 0.63,
 0.13,
 0.0675,
 2.66,
 160500000.0,
 58100000.0,
 83700000.0,
 979700000.0,
 109300000.0,
 32500000.0,
 6900000.0,
 9800000.0,
 2365000000.0,
 35400000.0,
 445000000.0,
 0.0538,
 89500000.0,
 38300000.0,
 12700000.0,
 755100000.0,
 268700000.0,
 450800000.0,
 246000000.0,
 27970800000.0,
 15600000.0,
 906400000.0,
 44100000.0,
 18500000.0,
 3090500000.0,
 69700000.0,
 274500000.0,
 5141400000.0,
 251800000.0,
 47000000.0,
 19093400000.0,
 3579800000.0,
 21400000.0,
 6907800000.0,
 72600000.0,
 4248300000.0,
 5118700000.0,
 180800000.0,
 1000000000.0,
 27200000.0,
 308800000.0,
 232000000.0,
 0.47,
 1600000.0,
 129600000.0,
 334400000.0,
 52800000.0,
 3204500000.0,
 337300000.0,
 81300000.0,
 4500000.0,
 234900000.0,
 1722600000.0,
 161000000.0,
 7400000.0,
 0.0386,
 35900000.0,
 189500000.0,
 138300000.0,
 547900000.0,
 61500000.0,
 141200000.0,
 115600000.0,
 38800000.0,
 90000000.0,
 499600000.0,
 16100000.0,
 144100000.0,
 1500900000.0,
 886500000.0,
 579300000.0,
 195300000.0,
 300600000.0,
 70200000.0,
 2015800000.0,
 19000000.0,
 633400000.0,
 761400000.0,
 0.0371,
 149900000.0,
 687500000.0,
 98700000.0,
 380300000.0,
 1199500000.0,
 124300000.0,
 178400000.0,
 24800000.0,
 255200000.0,
 306400000.0,
 1100000000.0,
 127200000.0,
 2100000.0,
 130100000.0,
 53300000.0,
 898100000.0,
 155700000.0,
 78900000.0,
 773000000.0,
 5000000.0,
 81800000.0,
 56200000.0,
 30600000.0,
 2030300000.0,
 110300000.0,
 7900000.0,
 59100000.0,
 1697500000.0,
 0.06,
 36400000.0,
 10800000.0,
 62000000.0,
 87600000.0,
 13700000.0,
 756100000.0,
 90500000.0,
 3000.0,
 1629400000.0,
 42200000.0,
 170200000.0,
 656600000.0,
 16600000.0,
 93400000.0,
 67800000.0,
 272600000.0,
 0.028,
 336202718.0,
 275500000.0,
 45100000.0,
 19500000.0,
 7929900000.0,
 915500000.0,
 224300000.0,
 99200000.0,
 22400000.0,
 1737600000.0,
 1200000000.0,
 3888000000.0,
 2.72,
 48000000.0,
 76500000.0,
 50900000.0,
 25300000.0,
 306900000.0,
 1333800000.0,
 949800000.0,
 335400000.0,
 79400000.0,
 2600000.0,
 28200000.0,
 25426300000.0,
 31100000.0,
 5253500000.0,
 415100000.0,
 466300000.0,
 1774800000.0,
 110800000.0,
 8400000.0,
 3157200000.0,
 136400000.0,
 34000000.0,
 574500000.0,
 497700000.0,
 14200000.0,
 91000000.0,
 0.15,
 145100000.0,
 273100000.0,
 7825100000.0,
 17100000.0,
 247500000.0,
 68300000.0,
 2884300000.0,
 119500000.0,
 196300000.0,
 173600000.0,
 20000000.0,
 71200000.0,
 0.4,
 0.65,
 0.9,
 506400000.0,
 48500000.0,
 2019700000.0,
 22900000.0,
 99700000.0,
 3021000000.0,
 153800000.0,
 77000000.0,
 205000000.0,
 333000000.0,
 51400000.0,
 200000.0,
 102600000.0,
 435400000.0,
 25800000.0,
 28700000.0,
 131100000.0,
 3100000.0,
 1846300000.0,
 2025500000.0,
 540700000.0,
 57200000.0,
 466800000.0,
 4358000000.0,
 108400000.0,
 6000000.0,
 825200000.0,
 2412400000.0,
 2950000000.0,
 1093000.0,
 697200000.0,
 136900000.0,
 8900000.0,
 341700000.0,
 34500000.0,
 162500000.0,
 114200000.0,
 165400000.0,
 11800000.0,
 3288600000.0,
 782700000.0,
 40300000.0,
 1550700000.0,
 14700000.0,
 17600000.0,
 0.24,
 1400000000.0,
 122900000.0,
 20500000.0,
 71700000.0,
 74600000.0,
 179900000.0,
 26300000.0,
 700000.0,
 128700000.0,
 51900000.0,
 54800000.0,
 29200000.0,
 106000000.0,
 8349200000.0,
 3600000.0,
 83300000.0,
 2054500000.0,
 876900000.0,
 313700000.0,
 6500000.0,
 111800000.0,
 1263800000.0,
 35000000.0,
 163000000.0,
 26915000000.0,
 239800000.0,
 188600000.0,
 9400000.0,
 37900000.0,
 498700000.0,
 293900000.0,
 63500000.0,
 396300000.0,
 12300000.0,
 15200000.0,
 885600000.0,
 2319200000.0,
 0.269,
 92000000.0,
 1500000000.0,
 325300000.0,
 18100000.0,
 1374900000.0,
 197300000.0,
 149000000.0,
 46600000.0,
 21000000.0,
 177500000.0,
 0.08,
 151900000.0,
 23900000.0,
 75100000.0,
 0.0175,
 26800000.0,
 78000000.0,
 180400000.0,
 462000000.0,
 0.33,
 1200000.0,
 720900000.0,
 29700000.0,
 4100000.0,
 132100000.0,
 10554200000.0,
 4333400000.0,
 83800000.0,
 7000000.0,
 58200000.0,
 37219586000.0,
 3977900000.0,
 35500000.0,
 4595200000.0,
 1600000000.0,
 2.67,
 12800000.0,
 64000000.0,
 2.92,
 38400000.0,
 11200000000.0,
 268800000.0,
 220500000.0,
 15700000.0,
 66900000.0,
 1935700000.0,
 44200000.0,
 223400000.0,
 146600000.0,
 940200000.0,
 453800000.0,
 4473000000.0,
 3400700000.0,
 72700000.0,
 0.0709,
 687100000.0,
 3480400000.0,
 5963600000.0,
 0.42,
 50000000.0,
 24400000.0,
 3278500000.0,
 27300000.0,
 0.045,
 1700000.0,
 155300000.0,
 232100000.0,
 385700000.0,
 257700000.0,
 209400000.0,
 4600000.0,
 2001400000.0,
 542200000.0,
 0.17,
 217294.0,
 1492300000.0,
 33100000.0,
 7500000.0,
 0.013,
 164000000.0,
 624800000.0,
 10400000.0,
 4388000000.0,
 138400000.0,
 266400000.0,
 676000000.0,
 61600000.0,
 36000000.0,
 14500000000.0,
 909300000.0,
 64500000.0,
 320500000.0,
 912200000.0,
 41800000.0,
 93000000.0,
 44700000.0,
 838300000.0,
 275100000.0,
 19100000.0,
 121500000.0,
 2502300000.0,
 1148400000.0,
 150000000.0,
 226800000.0,
 201200000.0,
 0.449,
 278000000.0,
 9750000000.0,
 50500000.0,
 127300000.0,
 76100000.0,
 639300000.0,
 229700000.0,
 255300000.0,
 24900000.0,
 1000600000.0,
 104600000.0,
 2075800000.0,
 2200000.0,
 2255000000.0,
 133100000.0,
 30700000.0,
 977900000.0,
 56300000.0,
 2513900000.0,
 926700000.0,
 107500000.0,
 0.0725,
 5100000.0,
 286700000.0,
 0.01,
 8000000.0,
 1.01,
 59200000.0,
 264000000.0,
 520000000.0,
 33600000.0,
 1364800000.0,
 3057300000.0,
 17162900000.0,
 5233300000.0,
 17367700000.0,
 241300000.0,
 87700000.0,
 292500000.0,
 10900000.0,
 321000000.0,
 141800000.0,
 65000000.0,
 167400000.0,
 244200000.0,
 90600000.0,
 13800000.0,
 784700000.0,
 375100000.0,
 170300000.0,
 16700000.0,
 42300000.0,
 323900000.0,
 250000000.0,
 838800000.0,
 122000000.0,
 19600000.0,
 966800000.0,
 506000000.0,
 124900000.0,
 22500000.0,
 0.039,
 1203000000.0,
 102200000.0,
 25400000.0,
 179000000.0,
 2636600000.0,
 153400000.0,
 335500000.0,
 2700000.0,
 0.6,
 1183200000.0,
 0.85,
 0.35,
 56800000.0,
 287200000.0,
 5600000.0,
 543200000.0,
 184800000.0,
 110900000.0,
 4027700000.0,
 366900000.0,
 290100000.0,
 1723700000.0,
 85300000.0,
 8500000.0,
 1086600000.0,
 62600000.0,
 113800000.0,
 0.1,
 421000000.0,
 165000000.0,
 88200000.0,
 11400000.0,
 216200000.0,
 65500000.0,
 577500000.0,
 1166300000.0,
 1476400000.0,
 6110000000.0,
 2730800000.0,
 17200000.0,
 71300000.0,
 199300000.0,
 916100000.0,
 20100000.0,
 276100000.0,
 3194500000.0,
 99800000.0,
 355800000.0,
 23000000.0,
 102700000.0,
 25900000.0,
 2227500000.0,
 300000.0,
 3225900000.0,
 3200000.0,
 156800000.0,
 80000000.0,
 28800000.0,
 592000000.0,
 2000000000.0,
 722900000.0,
 492500000.0,
 6100000.0,
 1081300000.0,
 9000000.0,
 111400000.0,
 11900000.0,
 37500000.0,
 267900000.0,
 63100000.0,
 194000000.0,
 40400000.0,
 66000000.0,
 14800000.0,
 0.44,
 0.065,
 0.19,
 145700000.0,
 171300000.0,
 17700000.0,
 196900000.0,
 5140600000.0,
 7700600000.0,
 100300000.0,
 23500000.0,
 0.001,
 205600000.0,
 800000.0,
 410400000.0,
 29300000.0,
 234100000.0,
 3700000.0,
 2512500000.0,
 54900000.0,
 106100000.0,
 3485300000.0,
 0.0757,
 109000000.0,
 1133000000.0,
 32200000.0,
 83400000.0,
 160200000.0,
 6600000.0,
 137500000.0,
 6179100000.0,
 60700000.0,
 0.0559,
 934000000.0,
 166000000.0,
 3673200000.0,
 319600000.0,
 1676400000.0,
 550000000.0,
 334402964.0,
 40900000.0,
 15300000.0,
 182100000.0,
 4316100000.0,
 69400000.0,
 18200000.0,
 43800000.0,
 95000000.0,
 0.0361,
 21100000.0,
 891500000.0,
 2225600000.0,
 126400000.0,
 228800000.0,
 24000000.0,
 152000000.0,
 ...]

In [29]:
len(valeant_nums)

1416

In [30]:
def first_digit(number):
    return int(str(number*100)[0])

In [31]:
benford_valeant = [first_digit(num) for num in valeant_nums] 
len(benford_valeant)

1416

In [32]:
benford_valeant

[0,
 2,
 2,
 5,
 2,
 1,
 2,
 1,
 3,
 4,
 5,
 6,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 2,
 7,
 2,
 3,
 4,
 1,
 1,
 3,
 5,
 1,
 4,
 5,
 5,
 5,
 6,
 6,
 5,
 3,
 3,
 1,
 5,
 7,
 8,
 8,
 9,
 3,
 8,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 8,
 4,
 1,
 1,
 1,
 1,
 4,
 1,
 2,
 2,
 3,
 8,
 3,
 1,
 4,
 2,
 1,
 3,
 3,
 2,
 1,
 2,
 3,
 1,
 3,
 5,
 7,
 8,
 3,
 1,
 2,
 2,
 3,
 5,
 1,
 9,
 9,
 3,
 2,
 1,
 8,
 6,
 1,
 1,
 8,
 3,
 5,
 2,
 6,
 1,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 6,
 1,
 1,
 8,
 1,
 1,
 1,
 6,
 2,
 4,
 3,
 7,
 4,
 1,
 2,
 2,
 4,
 1,
 7,
 1,
 7,
 9,
 1,
 2,
 1,
 7,
 7,
 1,
 7,
 6,
 5,
 2,
 2,
 5,
 3,
 6,
 6,
 8,
 4,
 1,
 3,
 2,
 5,
 6,
 8,
 6,
 4,
 1,
 1,
 3,
 2,
 1,
 4,
 2,
 1,
 7,
 5,
 2,
 1,
 6,
 1,
 7,
 1,
 1,
 9,
 9,
 8,
 2,
 2,
 2,
 6,
 1,
 2,
 4,
 1,
 2,
 1,
 5,
 1,
 4,
 5,
 1,
 3,
 1,
 5,
 9,
 1,
 5,
 6,
 6,
 3,
 1,
 3,
 3,
 1,
 2,
 8,
 2,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 4,
 2,
 6,
 2,
 1,
 4,
 7,
 2,
 2,
 1,
 1,
 5,
 2,
 7,
 2,
 1,
 1,
 1,
 1,
 9,
 5,
 5,
 8,
 5,
 7,
 1,
 1,
 3,
 1,
 3,
 5,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 1,
 1,
 2,
 2,
 1,
 4,
 2,
 8,
 3,
 7,
 3,
 2,
 2,
 5,
 1,
 2,
 2,
 2,
 1,
 5,
 1,
 1,
 3,
 5,
 1,
 1,
 5,
 3,
 8,
 8,
 8,
 5,
 1,
 6,
 1,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 6,
 1,
 2,
 9,
 4,
 1,
 3,
 7,
 1,
 9,
 4,
 1,
 4,
 1,
 1,
 4,
 2,
 1,
 2,
 2,
 7,
 1,
 1,
 1,
 5,
 2,
 4,
 2,
 2,
 6,
 6,
 3,
 2,
 5,
 5,
 5,
 3,
 2,
 2,
 3,
 5,
 7,
 8,
 1,
 6,
 9,
 2,
 6,
 1,
 3,
 1,
 4,
 6,
 2,
 4,
 1,
 1,
 9,
 1,
 2,
 1,
 6,
 9,
 1,
 3,
 4,
 2,
 5,
 2,
 2,
 1,
 3,
 6,
 9,
 5,
 6,
 5,
 2,
 8,
 3,
 1,
 0,
 6,
 1,
 2,
 1,
 3,
 8,
 2,
 1,
 8,
 9,
 3,
 3,
 1,
 3,
 1,
 6,
 1,
 4,
 7,
 1,
 4,
 6,
 1,
 1,
 4,
 5,
 4,
 4,
 7,
 1,
 4,
 3,
 9,
 3,
 2,
 7,
 7,
 3,
 9,
 1,
 7,
 1,
 0,
 3,
 4,
 5,
 1,
 9,
 6,
 1,
 6,
 2,
 1,
 5,
 8,
 9,
 1,
 3,
 6,
 9,
 2,
 3,
 4,
 5,
 8,
 3,
 1,
 7,
 2,
 4,
 2,
 2,
 1,
 9,
 4,
 1,
 3,
 6,
 2,
 5,
 2,
 4,
 1,
 3,
 2,
 6,
 7,
 4,
 5,
 1,
 1,
 2,
 3,
 2,
 4,
 1,
 1,
 3,
 5,
 3,
 3,
 8,
 4,
 2,
 1,
 1,
 7,
 3,
 3,
 1,
 1,
 5,
 6,
 1,
 1,
 3,
 9,
 4,
 1,
 1,
 1,
 8,
 5,
 1,
 3,
 7,
 2,
 1,
 6,
 7,
 3,
 1,
 6,
 9,
 3,
 1,
 1,
 1,
 2,
 2,
 3,
 1,
 1,
 2,
 1,
 5,
 8,
 1,
 7,
 7,
 5,
 8,
 5,
 3,
 2,
 1,
 7,
 5,
 1,
 6,
 3,
 1,
 6,
 8,
 1,
 7,
 9,
 3,
 1,
 4,
 1,
 6,
 1,
 9,
 6,
 2,
 2,
 3,
 2,
 4,
 1,
 7,
 9,
 2,
 9,
 2,
 1,
 1,
 3,
 2,
 4,
 7,
 5,
 2,
 3,
 1,
 9,
 3,
 7,
 2,
 2,
 2,
 3,
 5,
 4,
 4,
 1,
 1,
 8,
 3,
 1,
 3,
 5,
 4,
 1,
 9,
 1,
 1,
 2,
 7,
 1,
 2,
 6,
 2,
 1,
 1,
 1,
 2,
 7,
 4,
 6,
 9,
 5,
 4,
 2,
 2,
 9,
 3,
 1,
 7,
 2,
 3,
 5,
 2,
 1,
 4,
 2,
 2,
 1,
 3,
 1,
 2,
 5,
 5,
 4,
 4,
 1,
 6,
 8,
 2,
 2,
 1,
 6,
 1,
 8,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 7,
 4,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 7,
 7,
 1,
 2,
 7,
 1,
 5,
 5,
 2,
 1,
 8,
 3,
 8,
 2,
 8,
 3,
 6,
 1,
 1,
 3,
 1,
 2,
 2,
 1,
 9,
 3,
 4,
 2,
 6,
 3,
 1,
 1,
 8,
 2,
 2,
 9,
 1,
 3,
 1,
 1,
 1,
 1,
 4,
 2,
 1,
 8,
 1,
 2,
 7,
 1,
 2,
 7,
 1,
 4,
 3,
 1,
 7,
 2,
 4,
 1,
 1,
 4,
 8,
 7,
 5,
 3,
 3,
 3,
 4,
 1,
 2,
 1,
 6,
 2,
 3,
 1,
 2,
 2,
 1,
 6,
 1,
 4,
 2,
 1,
 9,
 4,
 4,
 3,
 7,
 7,
 6,
 3,
 5,
 4,
 5,
 2,
 3,
 2,
 4,
 1,
 1,
 2,
 3,
 2,
 2,
 4,
 2,
 5,
 1,
 2,
 1,
 3,
 7,
 1,
 1,
 6,
 1,
 4,
 1,
 2,
 6,
 6,
 3,
 1,
 9,
 6,
 3,
 9,
 4,
 9,
 4,
 8,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 4,
 2,
 9,
 5,
 1,
 7,
 6,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 3,
 9,
 5,
 2,
 9,
 1,
 7,
 5,
 2,
 1,
 8,
 1,
 5,
 2,
 5,
 3,
 1,
 3,
 1,
 5,
 1,
 2,
 8,
 2,
 1,
 3,
 1,
 6,
 1,
 2,
 9,
 1,
 7,
 3,
 1,
 1,
 4,
 3,
 2,
 8,
 1,
 1,
 9,
 5,
 1,
 2,
 3,
 1,
 1,
 2,
 1,
 2,
 1,
 3,
 2,
 6,
 1,
 8,
 3,
 5,
 2,
 5,
 5,
 1,
 1,
 4,
 3,
 2,
 1,
 8,
 8,
 1,
 6,
 1,
 1,
 4,
 1,
 8,
 1,
 2,
 6,
 5,
 1,
 1,
 6,
 2,
 1,
 7,
 1,
 9,
 2,
 2,
 3,
 9,
 3,
 2,
 1,
 2,
 2,
 3,
 3,
 3,
 1,
 8,
 2,
 5,
 2,
 7,
 4,
 6,
 1,
 9,
 1,
 1,
 3,
 2,
 6,
 1,
 4,
 6,
 1,
 4,
 6,
 1,
 1,
 1,
 1,
 1,
 5,
 7,
 1,
 2,
 0,
 2,
 8,
 4,
 2,
 2,
 3,
 2,
 5,
 1,
 3,
 7,
 1,
 1,
 3,
 8,
 1,
 6,
 1,
 6,
 6,
 5,
 9,
 1,
 3,
 3,
 1,
 5,
 3,
 4,
 1,
 1,
 4,
 6,
 1,
 4,
 9,
 3,
 2,
 8,
 2,
 1,
 2,
 2,
 1,
 ...]

In [33]:
def frequencies(first_digits):
    counts = [0]*10
    for x in first_digits:
        if x > 0:
            counts[x] += 1 
    total = sum(counts)
    freq = [count/total for count in counts]
#     print(sum(freq))
    return freq[1:] #same as going from element 1 through the end (i.e. 9)

In [34]:
frequencies(benford_valeant)

[0.31063829787234043,
 0.18581560283687942,
 0.12340425531914893,
 0.07588652482269503,
 0.07801418439716312,
 0.06595744680851064,
 0.05602836879432624,
 0.05390070921985816,
 0.05035460992907802]

In [35]:
import math
r = range(10)
benfords_law = [math.log10(1 + 1/digit) for digit in r if digit != 0]
benfords_law

[0.3010299956639812,
 0.17609125905568124,
 0.12493873660829993,
 0.09691001300805642,
 0.07918124604762482,
 0.06694678963061322,
 0.05799194697768673,
 0.05115252244738129,
 0.04575749056067514]

In [36]:
len(benford_valeant)

1416

In [37]:
import plotly

plotly.offline.init_notebook_mode(connected=True)
Benfords_Law = {'type': 'scatter', 'x': list(range(1, 10)), 'y': benfords_law}
Valeant = {'type': 'scatter', 'x': list(range(1, 10)), 'y': frequencies(benford_valeant)}


plotly.offline.iplot([Benfords_Law, Valeant])

In [55]:
import math
def kl_divergence(freq):
    kl_div = 0.0
    for d in range(1, 10):
        Q = (math.log(d+1) - math.log(d)) / math.log(10) #calculates theoretical benfords (perfect benny freqs)
        P = freq[d-1]
        kl_div += math.log(P / Q) * P
#         print((freq))

    return round(float(kl_div),3)

In [56]:
kl_divergence(frequencies(benford_valeant))

0.003

In [57]:
kl_divergence(benfords_law)

0.0

In [ ]:
# q414numbers.join(s.apply(lambda x: x.split('-')))

In [ ]:
# q414numbers= q414numbers.drop('adsh', axis=1).join(s.reset_index(drop=True, level=1).rename(['0'],['1'],['2']))

In [ ]:
# q414numbers.head()

In [ ]:
import numpy as np
import random
def p_value(freq):
    n = sum(freq)
    ps = [(math.log(d+1) - math.log(d)) / math.log(10) for d in range(1, 10)]

    ks_obs = freq[1:]

    def ll(ks): # log-likelihood
        z = random.sample(zip(ks, ps), 8)
        return sum([k * math.log(p) for (k, p) in z])

    N = 10000
    P = 0
    for i in range(N):
        ks = np.random.multinomial(n, ps)
        if ll(ks) > ll(ks_obs): P += 1

In [ ]:
p_value(benford_valeant)

In [ ]:
ks_obs = freq[1:]